SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_INS AI
RIGHT OUTER JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE "Intact%"
AND (AO.SEX_UPON_OUTCOME LIKE "Neutered%" OR AO.SEX_UPON_OUTCOME LIKE "Spayed%")
ORDER BY AO.ANIMAL_ID